config/routes.rb
Rails.application.routes.draw do
  resources :railway_stations
  get 'thought', to: 'thought#index'
  root 'chat_room#index'
  get 'signup', to: 'sessions#signup'
  post 'register', to: 'sessions#register'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#authenticate'
  delete 'logout', to: 'sessions#destroy'

  resources :trains

  namespace :admin do
    resources :routes
  end
  post 'message', to: 'messages#create'

  mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ActiveRecord::Base
  has_many :carriages

  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end
  def show; end
  def edit; end
  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end

  end

  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Railway station was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
    end
  end

  private
  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/views/trains/_form.html.erb
<%= form_with(model: train, local: true) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

      <ul>
        <% train.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :current_station, 'Current Station' %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= form.submit 'Create'%>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Trainn</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trains.each do |train| %>
    <tr>
      <td><%= train.number %></td>
      <td><%= link_to 'Show', train %></td>
      <td><%= link_to 'Edit', edit_train_path(train) %></td>
      <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>На станции:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Не указано
  <% end %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>